import { useRef, useState, useEffect } from 'react'
import html2canvas from 'html2canvas'

function ImageCards({ result, branding, colorTheme, onExportPDF }) {
  const instaRefs = useRef([])
  const linkedinRefs = useRef([])
  const twitterRefs = useRef([])
  const instaScrollRef = useRef(null)
  const linkedinScrollRef = useRef(null)
  const twitterScrollRef = useRef(null)
  const [showExportMenu, setShowExportMenu] = useState(false)
  const exportRef = useRef(null)

  // Close export menu on outside click
  useEffect(() => {
    const handleClick = (e) => {
      if (exportRef.current && !exportRef.current.contains(e.target)) {
        setShowExportMenu(false)
      }
    }
    if (showExportMenu) {
      document.addEventListener('mousedown', handleClick)
    }
    return () => document.removeEventListener('mousedown', handleClick)
  }, [showExportMenu])

  // Editable slides state — initialized from AI result
  const [instaSlides, setInstaSlides] = useState(result.instagram?.carousel || [])
  const [linkedinSlides, setLinkedinSlides] = useState(result.linkedin?.carousel || [])
  const [twitterSlides, setTwitterSlides] = useState(result.twitter?.carousel || [])

  const updateSlide = (setter, slides, index, field, value) => {
    const updated = [...slides]
    updated[index] = { ...updated[index], [field]: value }
    setter(updated)
  }

  const downloadImage = async (ref, filename) => {
    if (!ref) return
    const canvas = await html2canvas(ref, {
      scale: 2,
      useCORS: true,
      backgroundColor: null,
    })
    const link = document.createElement('a')
    link.download = filename
    link.href = canvas.toDataURL('image/png')
    link.click()
  }

  const downloadPlatformSlides = async (refs, prefix) => {
    for (let i = 0; i < refs.current.length; i++) {
      if (refs.current[i]) {
        await downloadImage(refs.current[i], `${prefix}-slide-${i + 1}.png`)
      }
    }
  }

  const downloadAllText = () => {
    let text = `=== Generated by ContentForge ===\n\n`
    text += `--- SUMMARY ---\n${result.summary}\n\n`
    text += `--- INSTAGRAM ---\n${result.instagram?.caption}\n\n${result.instagram?.hashtags}\n\n`
    text += `--- LINKEDIN ---\n${result.linkedin?.post}\n\n`
    text += `--- X (TWITTER) THREAD ---\n${result.twitter?.thread?.map((t, i) => `${i + 1}/${result.twitter.thread.length} ${t}`).join('\n\n')}\n\n`
    text += `--- VIRAL HOOKS ---\n${result.hooks?.map((h, i) => `${i + 1}. ${h}`).join('\n')}\n`
    const blob = new Blob([text], { type: 'text/plain' })
    const link = document.createElement('a')
    link.download = 'contentforge-all-content.txt'
    link.href = URL.createObjectURL(blob)
    link.click()
  }

  // Platform-specific gradients
  const PLATFORM_GRADIENTS = {
    instagram: [
      'linear-gradient(135deg, #833ab4, #fd1d1d, #fcb045)',
      'linear-gradient(135deg, #e1306c, #c13584, #833ab4)',
      'linear-gradient(135deg, #fcb045, #fd1d1d, #833ab4)',
      'linear-gradient(160deg, #833ab4, #fcb045)',
      'linear-gradient(200deg, #fd1d1d, #833ab4)',
      'linear-gradient(45deg, #fcb045, #e1306c, #833ab4)',
    ],
    linkedin: [
      'linear-gradient(135deg, #0077b5, #004182, #1e3a5f)',
      'linear-gradient(135deg, #004182, #1e3a5f, #0077b5)',
      'linear-gradient(135deg, #1e3a5f, #0077b5, #004182)',
      'linear-gradient(160deg, #0077b5, #1e3a5f)',
      'linear-gradient(200deg, #004182, #0077b5)',
      'linear-gradient(45deg, #1e3a5f, #004182, #0077b5)',
    ],
    twitter: [
      'linear-gradient(135deg, #0f172a, #1e293b, #06b6d4)',
      'linear-gradient(135deg, #1e293b, #06b6d4, #0f172a)',
      'linear-gradient(135deg, #06b6d4, #0f172a, #1e293b)',
      'linear-gradient(160deg, #0f172a, #06b6d4)',
      'linear-gradient(200deg, #1e293b, #0f172a)',
      'linear-gradient(45deg, #06b6d4, #1e293b, #0f172a)',
    ],
  }

  // Generate gradient variations from user's chosen color theme
  // Default: platform-specific gradients. If user picks a color theme (not default), override.
  const makeGradient = (index, platform) => {
    // If user hasn't changed from default (index 0), use platform-specific gradients
    if (branding.colorTheme === 0) {
      const platformGrads = PLATFORM_GRADIENTS[platform]
      if (platformGrads) return platformGrads[index % platformGrads.length]
    }
    // User picked a custom color theme — use their choice
    const c = colorTheme.colors
    const variations = [
      `linear-gradient(135deg, ${c[0]}, ${c[1]}, ${c[2]})`,
      `linear-gradient(135deg, ${c[1]}, ${c[2]}, ${c[0]})`,
      `linear-gradient(135deg, ${c[2]}, ${c[0]}, ${c[1]})`,
      `linear-gradient(160deg, ${c[0]}, ${c[2]})`,
      `linear-gradient(200deg, ${c[1]}, ${c[0]})`,
      `linear-gradient(45deg, ${c[2]}, ${c[1]}, ${c[0]})`,
    ]
    return variations[index % variations.length]
  }

  const getPlatformHandle = (platform) => {
    if (platform === 'instagram') return branding.instagram
    if (platform === 'linkedin') return branding.linkedin
    if (platform === 'twitter') return branding.twitter
    return branding.name
  }

  const scrollToSlide = (scrollRef, index, slideWidth) => {
    if (scrollRef.current) {
      scrollRef.current.scrollTo({ left: index * (slideWidth + 16), behavior: 'smooth' })
    }
  }

  const renderCarousel = (slides, setter, platform, refs, scrollRef, label, aspectClass, slideWidth) => (
    <div className={`platform-carousel platform-${platform}`}>
      <div className="platform-header">
        <h3>{label}</h3>
        <span className="slide-count">{slides.length} slides • Click text to edit</span>
      </div>
      {/* Thumbnail Navigation */}
      <div className="slide-nav-pills">
        {slides.map((_, i) => (
          <button key={i} className="slide-nav-pill" onClick={() => scrollToSlide(scrollRef, i, slideWidth)}>
            {i + 1}
          </button>
        ))}
      </div>
      <div className="carousel-scroll" ref={scrollRef}>
        {slides.map((slide, index) => (
          <div className="carousel-slide-wrapper" key={index}>
            <span className="slide-number">Slide {index + 1} of {slides.length}</span>
            <div
              ref={(el) => (refs.current[index] = el)}
              className={`carousel-slide ${aspectClass}`}
              style={{ background: makeGradient(index, platform) }}
            >
              <div className="carousel-overlay"></div>
              <div className="carousel-content">
                <div className="carousel-emoji">{slide.emoji || '💡'}</div>
                <h3 className="carousel-title">{slide.title}</h3>
                <p className="carousel-body">{slide.body}</p>
                <div className="carousel-footer-bar">
                  <span>{getPlatformHandle(platform)}</span>
                  <span>{index < slides.length - 1 ? 'Swipe →' : '♥ Save this!'}</span>
                </div>
              </div>
            </div>
            {/* Editable fields below each slide */}
            <div className="slide-edit">
              <div className="slide-edit-label">✏️ Edit slide text (changes appear on slide above)</div>
              <input
                className="slide-edit-title"
                value={slide.title}
                onChange={(e) => updateSlide(setter, slides, index, 'title', e.target.value)}
                placeholder="Slide title"
              />
              <textarea
                className="slide-edit-body"
                value={slide.body}
                onChange={(e) => updateSlide(setter, slides, index, 'body', e.target.value)}
                placeholder="Slide content"
                rows={2}
              />
            </div>
          </div>
        ))}
      </div>
      <button className="download-platform-btn" onClick={() => downloadPlatformSlides(refs, `${branding.name.toLowerCase().replace(/\s+/g, '')}-${platform}`)}>
        ⬇️ Download {label.split(' ').slice(1).join(' ')} PNGs
      </button>
    </div>
  )

  return (
    <div className="image-cards-section">
      <h2 className="section-title">🖼️ Ready-to-Post Platform Carousels</h2>
      <p className="section-subtitle">Editable carousel slides generated for Instagram, LinkedIn, and X.</p>

      {instaSlides.length > 0 && renderCarousel(instaSlides, setInstaSlides, 'instagram', instaRefs, instaScrollRef, '📸 Instagram Carousel', 'slide-square', 300)}
      {linkedinSlides.length > 0 && renderCarousel(linkedinSlides, setLinkedinSlides, 'linkedin', linkedinRefs, linkedinScrollRef, '💼 LinkedIn Carousel', 'slide-landscape', 380)}
      {twitterSlides.length > 0 && renderCarousel(twitterSlides, setTwitterSlides, 'twitter', twitterRefs, twitterScrollRef, '𝕏  Twitter Carousel', 'slide-wide', 400)}

      {/* Download All */}
      <div className="download-actions">
        <button
          className="download-all-btn"
          onClick={async () => {
            await downloadPlatformSlides(instaRefs, `${branding.name.toLowerCase().replace(/\s+/g, '')}-instagram`)
            await downloadPlatformSlides(linkedinRefs, `${branding.name.toLowerCase().replace(/\s+/g, '')}-linkedin`)
            await downloadPlatformSlides(twitterRefs, `${branding.name.toLowerCase().replace(/\s+/g, '')}-twitter`)
          }}
        >
          📦 Download All Images ({instaSlides.length + linkedinSlides.length + twitterSlides.length} slides)
        </button>
        <div className="export-dropdown-wrapper" ref={exportRef}>
          <button className="download-text-btn" onClick={() => setShowExportMenu(!showExportMenu)}>
            📄 Export Content ▾
          </button>
          {showExportMenu && (
            <div className="export-dropdown">
              <button onClick={() => { downloadAllText(); setShowExportMenu(false) }}>📝 Download as Text (.txt)</button>
              <button onClick={() => { onExportPDF(); setShowExportMenu(false) }}>📄 Download as PDF</button>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

export default ImageCards
